# Generated by Django 4.2.9 on 2024-01-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('deskripsi', models.TextField()),
                ('views', models.IntegerField()),
                ('branches', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
