# Generated by Django 4.2.9 on 2024-01-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_discoverthread_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discoverthread',
            old_name='deskripsi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='discoverthread',
            old_name='judul',
            new_name='title',
        ),
    ]
